### ISSUE TITLE
Consider turning this project into a tutorial

### ISSUE THREAD

**Issue by shengchalover** [nalexn/clean-architecture-swiftui#1]
Hey there,

I am a novice in programming, and I struggle grasping architectures very much. That SwiftUI / Combine are so new does not help a bit, as the dust is definitely not settled yet, and seems like very few really understand how to design with new frameworks.

This project (just as your posts btw) reads very easily, yet I still struggle understanding the core 'why's of the architecture, not to say that I cannot see the whole picture well.

If turned into a tutorial with detailed explanations and rationales describing the architecture, this becomes a goto place to learn how SwiftUI / Combine apps are designed. By tutorial I mean something akin to Apple's (unfortunately very non-informative) multi-step tutorial residing on /tutorials page.

This seems like not an easy task, but maybe other experienced devs can join this initiative.

Thanks!

**Comment by nalexn** [comment]
Hi @shengchalover 

Since you're a novice in programming in general, I would highly recommend you to not concentrate on the architectures for now. Just try to get used to the IDE, language features, frameworks, etc.

I elaborate more on this topic in [this comment on Medium](https://medium.com/@nalexn/i-wanted-to-try-building-my-first-swift-app-and-already-spent-2-weeks-learning-best-practices-and-37254aa58460).

There is a wonderful [SwiftUI tutorial from Apple](https://developer.apple.com/tutorials/swiftui/tutorials) that would help you get started. Just take it as the base, and follow the steps in the tutorial, but don't forget to experiment along the way. This is the best way to learn.

**Comment by nalexn** [comment]
I just noticed you're aware of Apple's tutorial. Yea, I'm planning to write an article describing the motivation behind tech design in general and this architecture in particular. Stay tuned!

**Comment by nalexn** [comment]
Hey @shengchalover 

I've just posted an [article](https://nalexn.github.io/separation-of-concerns/) that mainly covers what you've requested. Please let me know if some other things still need clarification!

**Comment by shengchalover** [comment]
Thanks a lot!
