### ISSUE TITLE
Question: presenting another same view in view hierarchy 

### ISSUE THREAD

**Issue by iomark** [nalexn/clean-architecture-swiftui#11]
Hello Alex,

Thank you for your architecture example and articles, they are awesome and help me a lot to understand how to work with SwiftUI. 

I would like to ask you about more complex navigation in the example. For example, the application has to show CountryDetails from ModalDetailsView. I tried to implement this in fork https://github.com/iomark/clean-architecture-swiftui/tree/test/same_view . As you can see it leads to weird effects. Could you advise how to resolve similar use cases related to using a view that already is presented in view hierarchy? As I understand the application routing state should resolve it in some way.

**Comment by nalexn** [comment]
Hi @iomark,

This is indeed a really weird UI effect! From my observation, the current revision of NavigationView in SwiftUI is [broken](https://github.com/nalexn/clean-architecture-swiftui/issues/4): its inner state management is totally screwed up.

If you replace one line of code from what you have:

```swift
Group {
            NavigationLink(
                destination: CountryDetails(country: country), //
                isActive: routingBinding.countryDetailsPresented,
                label: { EmptyView() })
        }
```

to this:

```swift
Group {
            NavigationLink(
                destination: Text("Country details"), //
                isActive: routingBinding.countryDetailsPresented,
                label: { EmptyView() })
        }
```
... the effect will go away (with one if (1)). Although we have a modally presented country details screen with **its own** NavigationView, SwiftUI tries to push the new screen to the **original** NavigationView instead fo the new one. Because of this, SwiftUI falls in an infinite loop of presenting child views.

(1) The back navigation will again be broken for the iOS simulator (you can find a hard-fix for this issue implemented in the project and discussed in the issue I mentioned above).

So, if you want to **navigate back** to the presented CountryDetails, you can simply toggle the presentation of the modal screen with routing parameters. If we indeed need to present a new CountryDetails in the new navigation stack, apparently we should find a way to trick SwiftUI by wrapping the screen in a dummy view, just so it would refrain from using the wrong navigation stack.

**Comment by iomark** [comment]
thank you for the detailed answer.

Is it possible that two CountryDetails view instances use the same AppState.routing.countryDetails.detailsSheet bool state variable and it leads to presenting new ModalDetails view that uses single common AppState.routing.modalDetails.countryDetailsPresented and the cycle repeats again and again?

**Comment by iomark** [comment]
My fork branch has logging AppState.routing.didSet and view path 
**CountryList->(Select Afghanistan)->CountryDetails->(Tap Flag)->ModalDetails->(Tap Show Country)->(Infinite View Presenting Loop)** 
has next log:

AppState, routing: 
AppState.ViewRouting:
  countriesList: CountriesList.Routing, countryDetails: AFG
  countryDetails: CountryDetails.Routing, detailsSheet: false
  modalDetails: ModalDetailsView.Routing, countryDetailsPresented: false

AppState, routing: 
AppState.ViewRouting:
  countriesList: CountriesList.Routing, countryDetails: AFG
  countryDetails: CountryDetails.Routing, detailsSheet: true
  modalDetails: ModalDetailsView.Routing, countryDetailsPresented: false

AppState, routing: 
AppState.ViewRouting:
  countriesList: CountriesList.Routing, countryDetails: AFG
  countryDetails: CountryDetails.Routing, detailsSheet: true
  modalDetails: ModalDetailsView.Routing, countryDetailsPresented: true

**Comment by nalexn** [comment]
> Is it possible that two CountryDetails view instances use the same AppState.routing.countryDetails.detailsSheet bool state variable and it leads to presenting new ModalDetails view that uses single common AppState.routing.modalDetails.countryDetailsPresented and the cycle repeats again and again?

That is correct. If we want to present two identical views in different places in the hierarchy with connected programmatic navigation, the screens must not share the presentation state.

We'd need to have separate variables in the AppState and guide the view upon construction which state variable to use (inject as init parameter for the view)
