### ISSUE TITLE
Question: AppLaunch Time and Memory management for Store

### ISSUE THREAD

**Issue by fernandocardenasm** [nalexn/clean-architecture-swiftui#24]
First of all, thanks for the great demo.

I have two questions when the App gets bigger and it needs many Services:
1. You initilaize the store before the app Lauch in AppEnvironment.bootstrap(), wouldnt it have a negative impact in the app launch time.
2. Once a service or state is created, it will remain in memory in the Store, wouldnt that affect the app performance or take to much memory when the are many services or states? Would it make sense to somehow deinit some of the unused states or services.

**Comment by nalexn** [comment]
Let's estimate the memory impact of the growing AppState and Services.

Services mostly don't have their own state (they rely on the AppState), so every instance takes up just the memory required to keep an empty struct (or object) in memory, which can be estimated as 8 bytes pointer in 64-bit OS. So if our app had 100 various services, the memory footprint would be still less than 1KB, which is nothing.

AppState, or the other hand, in some cases, can be consuming much memory, but I can see not too many scenarios when this might happen:
1. You introduce a collection type (Array, Set, Dictionary) that caches enormous amounts of data. For example, you're loading the entire Contacts database in memory. I knew people who had 5000 contacts in their phones, so this could easily take up a few megabytes of RAM, depending on how much memory is required for a single contact data structure.
2. You cache large media files in memory, such as Images, Videos, etc. Quite obviously you need to use NSCache or other solutions instead of retaining such objects in memory without proper management of their lifetime.

Other than that, imagine your app has grown to have 100 screens. Suppose, each screen requires a bunch of state variables, let's say, 10 each, varying from 1-bit booleans to ~1KB Array that caches some data for immediate display on the screen. Even if you load all 100 screens and fill out all its caches, the maximum memory footprint will be less than 1MB! A single photo of my cat weights 8 times more!

AppState has another huge advantage - it is a struct. So the compiler knows its size, which means this struct can be created within a nanosecond, regardless of how big it is - it's just one memory allocation instruction, as opposed to creating a tree of objects, where each object requires independent memory allocation. SwiftUI uses structs for the viewgraph exactly for this reason - structs can be created and deep-copied with just a couple of machine instructions.

So I would not worry about increasing the launch time because of the large AppState.

What does increase the memory consumption along with the app launch times, are the dynamic frameworks and libraries (especially from third-party). A weight of just one library can easily be more than 5-10 MB, which of course has impact on the launch performance.
