### ISSUE TITLE
@ObservedObject ViewModels

### ISSUE THREAD

**Issue by RustamG** [nalexn/clean-architecture-swiftui#30]
Hi Alexey. 

I see you are using `@ObservedObject` for ViewModels in [MVVM branch](https://github.com/nalexn/clean-architecture-swiftui/tree/mvvm). Earlier you posted an [article](https://nalexn.github.io/swiftui-observableobject/) why you quit using `@ObservableObject`. The main point of not using it is that you cannot simply compare ViewModels when implementing `Equatable` for the views because they reference the same ViewModels.

Do you have any idea on how implement `Equatable` for the views if the state is stored inside ViewModels?

**Comment by nalexn** [comment]
Hey @RustamG , yes, `ObservableObject` may introduce performance overhead when there are hundreds of views observing it (the case of Redux-like application with the centralized state). If there are just views inside one screen that are subscribed on a single `ObservableObject` (like with MVVM), the issue is not so apparent and convenience can take precedence over the performance harm (which is minimal in this case).

Majid [wrote an article](https://swiftwithmajid.com/2020/01/22/optimizing-views-in-swiftui-using-equatableview/) about how to structure the SwiftUI views so that `Equatable` would actually work as expected. In short: you have to split the view in two counterparts - one that references `@ObservedObject` or any other SwiftUI state, and another - that consumes that state as static data and renders it.

**Comment by RustamG** [comment]
Thanks for the tip @nalexn. Will give it a try
