### ISSUE TITLE
Any update for SwiftUI 2.0?

### ISSUE THREAD

**Issue by pnghai** [nalexn/clean-architecture-swiftui#40]
Hi, I checked that iOS 14 has transitioned into new life cycle (https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md), do you intent to make any update for it?

**Comment by Andhar7** [comment]
Hi, thank you Sent using the WEB.DE mail appOn 12.10.20 at 15:38, Hai Phan Nguyen wrote:
                
            
            
                
                    From: "Hai Phan Nguyen" <notifications@github.com>Date: 12 October 2020To: "nalexn/clean-architecture-swiftui" <clean-architecture-swiftui@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: [nalexn/clean-architecture-swiftui] Any update for SwiftUI 2.0? (#40)
                
                
Hi, I checked that iOS 14 has transitioned into new life cycle (https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md), do you intent to make any update for it?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nalexn/clean-architecture-swiftui/issues/40",
"url": "https://github.com/nalexn/clean-architecture-swiftui/issues/40",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nalexn** [comment]
Hey @pnghai 

For now, I'm thinking that support for iOS 13 overweights the benefits of migrating the app delegate. Its current revision is extremely minimal, with all the business logic extracted to other modules, so I don't see much value (in terms of reference for others) in reworking it with @main. If you don't mind I'd just post here a sample code of migrated delegate later

**Comment by nalexn** [comment]
The project has been finally migrated to use `@main`
