### ISSUE TITLE
More Please!

### ISSUE THREAD

**Issue by garsdle** [nalexn/clean-architecture-swiftui#7]
This is by far the best SwiftUI example I have found to date (and I keep up on this stuff!) 

I was wondering if you have any plans of adding some user actions, I am particularly curious how you would handling deletion of an item from a list. Again thank you so much for this resource.

**Comment by nalexn** [comment]
Thank you @garsdle ! I'll take a look at what you're asking, and either reply here with a code example or update the project to include this

**Comment by nalexn** [comment]
Hey @garsdle 

I've added a SearchBar, so the list of countries is now being filtered by the user input. This is not exactly the item deletion, so let me show how this could be done.

Since the deletion of an item implies committing this action to the backend, this change shouldn't be local to the view, as the countries' filtering feature is.

Based on that, I would follow [this example](https://www.hackingwithswift.com/quick-start/swiftui/how-to-enable-editing-on-a-list-using-editbutton) on making the List editable, and in the `onDelete` callback triggered a call on an `Interactor` instructing to make a networking call and remove the item with the selected `ID`.

Inside the networking callback in the `Interactor`, if the request is a success, we can simply update the `AppState` by removing the deleted item from the array.

This change will automatically be reflected in the UI.

Let me know if this answers your question.

**Comment by garsdle** [comment]
Awesome! Thank you so much for adding another great example

**Comment by alabdulaal** [comment]
> Hey @garsdle
> 
> I've added a SearchBar, so the list of countries is now being filtered by the user input. This is not exactly the item deletion, so let me show how this could be done.
> 
> Since the deletion of an item implies committing this action to the backend, this change shouldn't be local to the view, as the countries' filtering feature is.
> 
> Based on that, I would follow [this example](https://www.hackingwithswift.com/quick-start/swiftui/how-to-enable-editing-on-a-list-using-editbutton) on making the List editable, and in the `onDelete` callback triggered a call on an `Interactor` instructing to make a networking call and remove the item with the selected `ID`.
> 
> Inside the networking callback in the `Interactor`, if the request is a success, we can simply update the `AppState` by removing the deleted item from the array.
> 
> This change will automatically be reflected in the UI.
> 
> Let me know if this answers your question.

Hey @nalexn 

How would you go about removing or appending a new item since the array is immutable and composed in Loadable?

**Comment by nalexn** [comment]
@alabdulaal you need to compose a new Loadable and assign it in the AppState.

```swift
let oldValue = Loadable.loaded(["a", "b", "c"])
var array = oldValue.value ?? []
array.removeLast()
let newValue = Loadable.loaded(array)
// update AppState with the newValue
```

**Comment by alabdulaal** [comment]
@nalexn Thank you for your reply, wouldn't this approach hurt performance and result in unnecessary re-renders?

**Comment by nalexn** [comment]
It rather depends on the SwiftUI diffing engine, really. If you have a List that renders "A", "B" and "C" and need to render only "A", "B", you really have to feed the list with the **new array**. There is no other way.
You can use `EquatableView` if performance issues kicks in
